"use client"

import { Head } from "next/document";
import React, { useState } from "react";
import mainTheme from "../src/theme";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@mui/material";


export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isloaded, setIsloaded] = useState(false)

  return (
    <html lang="en">
      <Head>
        <title>Aid CrowdSource</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={mainTheme}>
        <body style={{
          backgroundColor: 'white',
          padding: 0
        }} >
          <Toaster />
          {
            isloaded == false ? <> </> : children}</body>
      </ThemeProvider>
    </html>
  )
}