"use client"

import { ThemeProvider } from "@emotion/react";
import { Head } from "next/document";
import React, { useState } from "react";
import mainTheme from "../src/theme";
import { Toaster } from "react-hot-toast";


export default function RootLayout({children}: {children: React.ReactNode}){
    const [isloaded, setIsloaded] = useState(false)

    return <ThemeProvider theme={mainTheme}>
    <html lang="en">
      <body style={{
        backgroundColor: 'white',
        padding: 0
      }} >
        <Head>
          <title>Aid CrowdSource</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Toaster />
        {
          isloaded == false ? <> </> : children}</body>
          </html>
          </ThemeProvider>
}