"use client"

import Head from "next/head";
import React, { useState } from "react";
import mainTheme from "../src/theme";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@mui/material";
// import ThemeProvider 


export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [isloaded, setIsloaded] = useState(false)

  return (
    <ThemeProvider theme={mainTheme}>
      <html lang="en">
        <Head>
          <title>Aid CrowdSource</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body style={{
          backgroundColor: 'white',
          padding: 0
        }} >
          {
            isloaded == false ? <> </> : children}</body>

      </html >
    </ThemeProvider>

  )
}